package main

// Links builds a collection of urls to target changlogs
type Links struct {
	ACF       string `json:"acf"`
	Calendar  string `json:"calendar"`
	Gravity   string `json:"gravity"`
	Poly      string `json:"poly"`
	Spotlight string `json:"spotlight"`
	Tickets   string `json:"tickets"`
	Virtual   string `json:"virtual"`
	WordPress string `json:"wordpress"`
	WPExport  string `json:"wpexport"`
}

// Atlassian builds a list of jira tokens and api addresses
type Atlassian struct {
	Base    string `json:"base"`
	Path    string `json:"path"`
	Token   string `json:"token"`
	Human   string `json:"human"`
	Issue   string `json:"issue"`
	Team    string `json:"team"`
	Project string `json:"project"`
	Source  string `json:"source"`
}

// Filters builds the parameters for sed to execute on the scrapped.txt file
type Filters struct {
	OPH2  string `json:"oph2"`
	OPH3  string `json:"oph3"`
	OPH4  string `json:"oph4"`
	CLH2  string `json:"clh2"`
	CLH3  string `json:"clh3"`
	CLH4  string `json:"clh4"`
	End   string `json:"end"`
	ESP   string `json:"esp"`
	Event string `json:"event"`
}

type AutoGenerated struct {
	Expand     string `json:"expand"`
	StartAt    int    `json:"startAt"`
	MaxResults int    `json:"maxResults"`
	Total      int    `json:"total"`
	Issues     []struct {
		Expand string `json:"expand"`
		ID     string `json:"id"`
		Self   string `json:"self"`
		Key    string `json:"key"`
	} `json:"issues"`
}

type Desso struct {
	Issues []struct {
		Key string `json:"key"`
	} `json:"issues"`
}

// Post contains the JSON parameters for a new Jira ticket
type Post struct {
	Issues []struct {
		Fields struct {
			Assignee struct {
				Key string `json:"key"`
			} `json:"assignee"`
			Issuetype struct {
				ID string `json:"id"`
			} `json:"issuetype"`
			Creator struct {
				Key string `json:"key"`
			} `json:"creator"`
			Labels   []string `json:"labels"`
			Reporter struct {
				Key string `json:"key"`
			} `json:"reporter"`
			Project struct {
				ID  string `json:"id"`
				Key string `json:"key"`
			} `json:"project"`
			Description string `json:"description"`
			Summary     string `json:"summary"`
		} `json:"fields"`
	} `json:"issues"`
}

const (
	header string = "\nh2. Changelog\n"
	bv     string = "1.0"
	halt   string = "program halted"
)

var (
	content   []byte
	label     string
	repo      string
	version   string
	filter    Filters
	jira      Atlassian
	link      Links
	post      Post
	title     Desso
	versions  = [1][2]string{{".", "-"}}
	jsons     = []string{jira.Path + "jsons/ticket.json", jira.Path + "jsons/filters.json", jira.Path + "jsons/links.json", jira.Path + "jsons/jira.json"}
	temp      = []string{jira.Path + "temp/grep.txt", jira.Path + "temp/scrape.txt"}
	deletions = []string{
		"<br />", "</h1>", "</h2>",
		"</h3>", "</h4>", "</li>",
		"<ul>", "</ul>", "</div>",
		"</div>", "<p>", "</p>",
		"<span>", "<entry>", "</entry>",
		"</span>", "<footer>", "</footer>",
		"<header>", "</header>",
	}
	replacements = [12][2]string{
		{"<h1>", "h1. "},
		{"<h2>", "h2. "},
		{"<h3>", "h3. "},
		{"<h4>", "h3. "},
		{"<li>", "- "},
		{"<strong>", "*"},
		{"</strong>", "*"},
		{"<em>", "*"},
		{"</em>", "*"},
		{"<code>", "*"},
		{"</code>", "*"},
		{"<li class=\"free\">", "- "},
	}
)
